// reactjs-components-integration/src/App.tsx
import type { DocumentCallback } from "@innovatrics/dot-document-auto-capture";
import type { FaceCallback } from "@innovatrics/dot-face-auto-capture";
import type { MagnifEyeLivenessCallback } from "@innovatrics/dot-magnifeye-liveness";
import { useCallback, useState } from "react";
import ComponentSelect from "./components/ComponentSelect";
import DocumentAutoCapture from "./components/DocumentAutoCapture";
import FaceAutoCapture from "./components/FaceAutoCapture";
import MagnifEyeLiveness from "./components/MagnifEyeLiveness";
import PhotoResult from "./components/PhotoResult";
import styles from "./styles/index.module.css";
import { Step } from "./types";

function App() {
  const [step, setStep] = useState<Step>(Step.SELECT_COMPONENT);
  const [photoUrl, setPhotoUrl] = useState<string>();

  const handlePhotoTaken = <T,>(image: Blob, data: T) => {
    const imageUrl = URL.createObjectURL(image);
    setPhotoUrl(imageUrl);
  };

  const handleDocumentPhotoTaken: DocumentCallback = (image, data) => {
    handlePhotoTaken(image, data);
  };

  const handleFaceCapturePhotoTaken: FaceCallback = (image, data) => {
    handlePhotoTaken(image, data);
  };

  const handleMagnifEyeComplete: MagnifEyeLivenessCallback = ({
    image,
    data,
  }) => {
    handlePhotoTaken(image, data);
  };

  const handleError = useCallback((error: Error) => {
    alert(error);
  }, []);

  const handleBackClick = () => {
    setPhotoUrl(undefined);
    setStep(Step.SELECT_COMPONENT);
  };

  const renderStep = (currentStep: Step) => {
    switch (currentStep) {
      case Step.DOCUMENT_CAPTURE:
        return (
          <>
            <DocumentAutoCapture
              onPhotoTaken={handleDocumentPhotoTaken}
              onError={handleError}
              onBackClick={handleBackClick}
            />
            {photoUrl && <PhotoResult photoUrl={photoUrl} />}
          </>
        );
      case Step.FACE_CAPTURE:
        return (
          <>
            <FaceAutoCapture
              onPhotoTaken={handleFaceCapturePhotoTaken}
              onError={handleError}
              onBackClick={handleBackClick}
            />
            {photoUrl && <PhotoResult photoUrl={photoUrl} />}
          </>
        );
      case Step.MAGNIFEYE_LIVENESS:
        return (
          <>
            <MagnifEyeLiveness
              onComplete={handleMagnifEyeComplete}
              onError={handleError}
              onBackClick={handleBackClick}
            />
            {photoUrl && <PhotoResult photoUrl={photoUrl} />}
          </>
        );
      default:
        return <ComponentSelect setStep={setStep} />;
    }
  };

  return (
    <div className={styles.app}>
      <h1>DOT Web Components Integration</h1>
      {renderStep(step)}
    </div>
  );
}

export default App;

// angular-components-integration/src/app/app.component.ts
import { Component } from '@angular/core';
import { OnPhotoTakenEventValue, Step } from './types';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  step: typeof Step = Step;
  currentStep: Step = Step.SELECT_COMPONENT;
  imageUrl = '';

  constructor() { }

  handleStepChange(step: Step) {
    this.currentStep = step;
    this.imageUrl = '';
  }

  handlePhotoTaken<T>({ imageData, content }: OnPhotoTakenEventValue<T>) {
    this.imageUrl = URL.createObjectURL(imageData.image);
  }

  handleError(error: Error) {
    alert(error);
  }
}

<div>
  <h1>DOT components integration</h1>
  <div *ngIf="currentStep === step.DOCUMENT_CAPTURE">
    <app-document-auto-capture
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-document-auto-capture>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.FACE_CAPTURE">
    <app-face-auto-capture
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-face-auto-capture>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.MAGNIFEYE_LIVENESS">
    <app-magnifeye-liveness
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-magnifeye-liveness>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.SMILE_LIVENESS">
    <app-smile-liveness
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-smile-liveness>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <app-component-select
    *ngIf="currentStep === step.SELECT_COMPONENT"
    (btnClick)="handleStepChange($event)"
  >
  </app-component-select>
</div>
