// react-ui-components-customization/src/App.tsx
import { useCallback, useState } from "react";
import "./styles/index.css";
import { FaceComponentCustomization } from "./components/FaceComponentCustomization";
import type {
  CallbackImage,
  FaceOnCompleteCallbackImage,
} from "@innovatrics/dot-face-auto-capture";

function App() {
  const [photoUrl, setPhotoUrl] = useState<string>();

  function handlePhotoTaken<T>(imageData: CallbackImage<T>) {
    const imageUrl = URL.createObjectURL(imageData.image);

    setPhotoUrl(imageUrl);
  }

  function handleFaceCapturePhotoTaken(imageData: FaceOnCompleteCallbackImage) {
    handlePhotoTaken(imageData);
  }

  const handleError = useCallback((error: Error) => {
    alert(error);
  }, []);

  return (
    <div className="app">
      <h1>Customized UI</h1>
      <FaceComponentCustomization
        onError={handleError}
        onPhotoTaken={handleFaceCapturePhotoTaken}
      />
      {photoUrl && (
        <div>
          <img alt="Web component result" src={photoUrl} />
        </div>
      )}
    </div>
  );
}

export default App;

// angular-components-integration/src/app/app.component.ts
import { Component } from '@angular/core';
import { OnPhotoTakenEventValue, Step } from './types';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  step: typeof Step = Step;
  currentStep: Step = Step.SELECT_COMPONENT;
  imageUrl = '';

  constructor() { }

  handleStepChange(step: Step) {
    this.currentStep = step;
    this.imageUrl = '';
  }

  handlePhotoTaken<T>({ imageData, content }: OnPhotoTakenEventValue<T>) {
    this.imageUrl = URL.createObjectURL(imageData.image);
  }

  handleError(error: Error) {
    alert(error);
  }
}

<div>
  <h1>DOT components integration</h1>
  <div *ngIf="currentStep === step.DOCUMENT_CAPTURE">
    <app-document-auto-capture
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-document-auto-capture>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.FACE_CAPTURE">
    <app-face-auto-capture
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-face-auto-capture>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.MAGNIFEYE_LIVENESS">
    <app-magnifeye-liveness
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-magnifeye-liveness>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <div *ngIf="currentStep === step.SMILE_LIVENESS">
    <app-smile-liveness
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
      (onBack)="handleStepChange($event)"
    >
    </app-smile-liveness>
    <app-result *ngIf="imageUrl" [imageUrl]="imageUrl"></app-result>
  </div>
  <app-component-select
    *ngIf="currentStep === step.SELECT_COMPONENT"
    (btnClick)="handleStepChange($event)"
  >
  </app-component-select>
</div>
