// angular-components-integration/src/app/components/document/document-ui.component.ts
import { Component, OnInit, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { HTMLDocumentUiElement } from '@innovatrics/dot-auto-capture-ui/document';
import '@innovatrics/dot-auto-capture-ui/document';

@Component({
  selector: 'app-document-ui',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<x-dot-document-auto-capture-ui
    id="x-dot-document-auto-capture-ui"
  />`,
  standalone: true,
})
export class DocumentUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initDocumentUi();
  }

  initDocumentUi() {
    const documentUiElement = document.getElementById(
      'x-dot-document-auto-capture-ui',
    ) as HTMLDocumentUiElement | null;

    if (documentUiElement) {
      documentUiElement.configuration = {
        control: {
          showCameraButtons: true,
        },
      };
    }
  }
}

// reactjs-components-integration/src/components/DocumentUi.tsx
import '@innovatrics/dot-auto-capture-ui/document';
import type { DocumentUiConfiguration, HTMLDocumentUiElement } from '@innovatrics/dot-auto-capture-ui/document';

import { useEffect } from 'react';

function DocumentUi(configuration: DocumentUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-document-auto-capture-ui') as HTMLDocumentUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-document-auto-capture-ui id="x-dot-document-auto-capture-ui" />;
}

export default DocumentUi;
