// angular-components-integration/src/app/components/document-ui/document-ui.component.ts
import { Component, OnInit } from '@angular/core';
import { HTMLDocumentUiElement } from '@innovatrics/dot-auto-capture-ui/document';
import '@innovatrics/dot-auto-capture-ui/document';

@Component({
  selector: 'app-document-ui',
  templateUrl: './document-ui.component.html',
  styleUrls: ['./document-ui.component.css'],
})
export class DocumentUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initDocumentUi();
  }

  initDocumentUi() {
    const documentUiElement = document.getElementById(
      'dot-document-auto-capture-ui'
    ) as HTMLDocumentUiElement | null;

    if (documentUiElement) {
      documentUiElement.props = {
        showCameraButtons: true,
      };
    }
  }
}

<x-dot-document-auto-capture-ui id="dot-document-auto-capture-ui"></x-dot-document-auto-capture-ui>

// reactjs-components-integration/src/components/DocumentUi.tsx
import "@innovatrics/dot-auto-capture-ui/document";
import { useEffect } from "react";
import type {
  DocumentUiProps,
  HTMLDocumentUiElement,
} from "@innovatrics/dot-auto-capture-ui/document";

function DocumentUi(props: DocumentUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-document-auto-capture-ui"
    ) as HTMLDocumentUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-document-auto-capture-ui id="x-dot-document-auto-capture-ui" />;
}

export default DocumentUi;
