// vuejs-components-integration/src/components/FaceUi.vue
<script setup lang="ts">
import type { FaceUiProps } from "@innovatrics/dot-auto-capture-ui/face";
import "@innovatrics/dot-auto-capture-ui/face";

type Props = {
  uiProps: FaceUiProps;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-face-auto-capture-ui .props="props.uiProps" />
</template>

// reactjs-components-integration/src/components/FaceUi.tsx
import type {
  FaceUiProps,
  HTMLFacetUiElement,
} from "@innovatrics/dot-auto-capture-ui/face";
import { useEffect } from "react";
import "@innovatrics/dot-auto-capture-ui/face";

const FaceUi = (props: FaceUiProps) => {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-face-auto-capture-ui"
    ) as HTMLFacetUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-face-auto-capture-ui id="x-dot-face-auto-capture-ui" />;
};

export default FaceUi;
