// angular-components-integration/src/app/components/magnifeye-liveness-ui/magnifeye-liveness-ui.component.ts
import { Component, OnInit } from '@angular/core';
import type { HTMLMagnifEyeLivenessUiElement } from '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';
import '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';

@Component({
  selector: 'app-magnifeye-liveness-ui',
  templateUrl: './magnifeye-liveness-ui.component.html',
  styleUrls: ['./magnifeye-liveness-ui.component.css']
})
export class MagnifEyeLivenessUiComponent implements OnInit {
  constructor() { }

  ngOnInit(): void {
    this.initMagnifEyeLivenessUi();
  }

  initMagnifEyeLivenessUi() {
    const magnifEyeUiElement = document.getElementById(
      'x-dot-magnifeye-liveness-ui'
    ) as HTMLMagnifEyeLivenessUiElement | null;

    if (magnifEyeUiElement) {
      magnifEyeUiElement.props = {
        showCameraButtons: true,
      };
    }
  }
}

<x-dot-magnifeye-liveness-ui
  id="x-dot-magnifeye-liveness-ui"
></x-dot-magnifeye-liveness-ui>

// reactjs-components-integration/src/components/MagnifEyeLivenessUi.tsx
import "@innovatrics/dot-auto-capture-ui/magnifeye-liveness";
import { useEffect } from "react";
import type {
  MagnifEyeLivenessUiProps,
  HTMLMagnifEyeLivenessUiElement,
} from "@innovatrics/dot-auto-capture-ui/magnifeye-liveness";

function MagnifEyeLivenessUi(props: MagnifEyeLivenessUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-magnifeye-liveness-ui",
    ) as HTMLMagnifEyeLivenessUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-magnifeye-liveness-ui id="x-dot-magnifeye-liveness-ui" />;
}

export default MagnifEyeLivenessUi;
