// vuejs-components-integration/src/components/MultiRangeLivenessUi.vue
<script setup lang="ts">
import type { MultiRangeUiConfiguration } from "@innovatrics/dot-auto-capture-ui/multi-range-liveness";
import '@innovatrics/dot-auto-capture-ui/multi-range-liveness';


type Props = {
  configuration: MultiRangeUiConfiguration;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-multi-range-liveness-ui .configuration="props.configuration" id="x-dot-multi-range-liveness-ui" />
</template>

// reactjs-components-integration/src/components/MultiRangeLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/multi-range-liveness';

import type {
  HTMLMultiRangeLivenessUiElement,
  MultiRangeUiConfiguration,
} from '@innovatrics/dot-auto-capture-ui/multi-range-liveness';

import { useEffect } from 'react';

function MultiRangeLivenessUi(configuration: MultiRangeUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById(
      'x-dot-multi-range-liveness-ui'
    ) as HTMLMultiRangeLivenessUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-multi-range-liveness-ui id="x-dot-multi-range-liveness-ui" />;
}

export default MultiRangeLivenessUi;
