// angular-components-integration/src/app/components/multi-range/multi-range-liveness.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import {
  ControlEventInstruction,
  dispatchControlEvent,
  MultiRangeCustomEvent,
} from '@innovatrics/dot-multi-range-liveness/events';

import { OnPhotoTakenEventValue, Step } from '../../types';

import { MultiRangeLivenessCameraComponent } from './multi-range-liveness-camera.component';
import { MultiRangeLivenessUiComponent } from './multi-range-liveness-ui.component';
import { DetectedFace } from '@innovatrics/dot-multi-range-liveness/ui-common/src/types/face';

@Component({
  selector: 'app-multi-range-liveness',
  standalone: true,
  imports: [MultiRangeLivenessCameraComponent, MultiRangeLivenessUiComponent],
  template: `
    <div>
      <h2>Multi Range Liveness</h2>
      <button (click)="onBackClick()" class="button">Go back</button>
      <button (click)="handleContinue()" class="button" [disabled]="isButtonDisabled">Continue detection</button>
      <div class="container">
        <app-multi-range-liveness-camera
          (photoTaken)="handlePhotoTaken($event)"
          (captureError)="handleError($event)"
        ></app-multi-range-liveness-camera>
        <app-multi-range-liveness-ui></app-multi-range-liveness-ui>
      </div>
    </div>
  `,
})
export class MultiRangeLivenessComponent {
  @Output() photoTaken = new EventEmitter<
  OnPhotoTakenEventValue<DetectedFace>
  >();
  @Output() captureError = new EventEmitter<Error>();
  @Output() back = new EventEmitter<Step>();

  isButtonDisabled = true;

  onBackClick() {
    this.back.emit(Step.SELECT_COMPONENT);
  }

  handleContinue() {
    dispatchControlEvent(MultiRangeCustomEvent.CONTROL, ControlEventInstruction.CONTINUE_DETECTION);

    this.isButtonDisabled = true;
  }

  handlePhotoTaken({ content, imageData }: OnPhotoTakenEventValue<DetectedFace>) {
    this.photoTaken.emit({ imageData, content });
    this.isButtonDisabled = false;
  }

  handleError(error: Error) {
    this.captureError.emit(error);
  }
}

// reactjs-components-integration/src/components/MultiRangeLiveness.tsx
import type { OnCompleteCallback } from '@innovatrics/dot-multi-range-liveness';

import {
  ControlEventInstruction,
  dispatchControlEvent,
  MultiRangeCustomEvent,
} from '@innovatrics/dot-multi-range-liveness/events';
import { useState } from 'react';

import buttonStyles from '../styles/button.module.css';
import styles from '../styles/index.module.css';

import MultiRangeLivenessCamera from './MultiRangeLivenessCamera';
import MultiRangeLivenessUi from './MultiRangeLivenessUi';

interface Props {
  onBackClick: () => void;
  onComplete: OnCompleteCallback;
  onError: (error: Error) => void;
}

function MultiRangeLiveness({ onBackClick, onComplete, onError }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  const handleOnComplete: OnCompleteCallback = async (imageData, content) => {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  };

  const handleContinueDetection = () => {
    dispatchControlEvent(
      MultiRangeCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION
    );

    setIsButtonDisabled(true);
  };

  return (
    <>
      <h2>MultiRange Liveness</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button
          className={buttonStyles.primary}
          disabled={isButtonDisabled}
          onClick={handleContinueDetection}
        >
          Continue detection
        </button>
      </div>
      <div className={styles.container}>
        <MultiRangeLivenessCamera
          challengeSequence={['ONE', 'THREE', 'FIVE', 'ZERO']}
          onComplete={handleOnComplete}
          onError={onError}
        />
        <MultiRangeLivenessUi showCameraButtons />
      </div>
    </>
  );
}

export default MultiRangeLiveness;
