// angular-components-integration/src/app/components/multi-range/multi-range-liveness-ui.component.ts
import type { OnInit } from '@angular/core';
import type { HTMLMultiRangeLivenessUiElement } from '@innovatrics/dot-auto-capture-ui/ui/src/types/multi-range';

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

import '@innovatrics/dot-auto-capture-ui/multi-range-liveness';

@Component({
  selector: 'app-multi-range-liveness-ui',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: ` <x-dot-multi-range-liveness-ui id="x-dot-multi-range-liveness-ui"></x-dot-multi-range-liveness-ui> `,
})
export class MultiRangeLivenessUiComponent implements OnInit {
  ngOnInit(): void {
    this.initMultiRangeLivenessUi();
  }

  initMultiRangeLivenessUi() {
    const multiRangeUiElement = document.getElementById(
      'x-dot-multi-range-liveness-ui',
    ) as HTMLMultiRangeLivenessUiElement | null;

    if (multiRangeUiElement) {
      multiRangeUiElement.props = {
        showCameraButtons: true,
      };
    }
  }
}

// reactjs-components-integration/src/components/MultiRangeLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/multi-range-liveness';

import type {
  HTMLMultiRangeLivenessUiElement,
  MultiRangeUiProps,
} from '@innovatrics/dot-auto-capture-ui/ui/src/types/multi-range';

import { useEffect } from 'react';

function MultiRangeLivenessUi(props: MultiRangeUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      'x-dot-multi-range-liveness-ui',
    ) as HTMLMultiRangeLivenessUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-multi-range-liveness-ui id="x-dot-multi-range-liveness-ui" />;
}

export default MultiRangeLivenessUi;
