// vuejs-components-integration/src/components/PalmUi.vue
<script setup lang="ts">
import type { PalmUiProps } from "@innovatrics/dot-auto-capture-ui/palm";
import "@innovatrics/dot-auto-capture-ui/palm";

type Props = {
  uiProps: PalmUiProps;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-palm-capture-ui .props="props.uiProps" id="x-dot-palm-capture-ui"/>
</template>

// reactjs-components-integration/src/components/PalmUi.tsx
import "@innovatrics/dot-auto-capture-ui/palm";
import { useEffect } from "react";
import type {
  PalmUiProps,
  HTMLPalmUiElement,
} from "@innovatrics/dot-auto-capture-ui/palm";

function PalmUi(props: PalmUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-palm-capture-ui",
    ) as HTMLPalmUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-palm-capture-ui id="x-dot-palm-capture-ui" />;
}

export default PalmUi;
