// angular-components-integration/src/app/components/smile-liveness-ui/smile-liveness-ui.component.ts
import { Component, OnInit } from '@angular/core';
import type { HTMLSmileLivenessUiElement } from '@innovatrics/dot-auto-capture-ui/smile-liveness';
import '@innovatrics/dot-auto-capture-ui/smile-liveness';

@Component({
  selector: 'app-smile-liveness-ui',
  templateUrl: './smile-liveness-ui.component.html',
  styleUrls: ['./smile-liveness-ui.component.css']
})
export class SmileLivenessUiComponent implements OnInit {
  constructor() { }

  ngOnInit(): void {
    this.initSmileLivenessUi();
  }

  initSmileLivenessUi() {
    const smileUiElement = document.getElementById(
      'x-dot-smile-liveness-ui'
    ) as HTMLSmileLivenessUiElement | null;

    if (smileUiElement) {
      smileUiElement.props = {
        showCameraButtons: true,
      };
    }
  }
}

<x-dot-smile-liveness-ui
  id="x-dot-smile-liveness-ui"
></x-dot-smile-liveness-ui>

// reactjs-components-integration/src/components/SmileLivenessUi.tsx
import "@innovatrics/dot-auto-capture-ui/smile-liveness";

import type {
  SmileLivenessUiProps,
  HTMLSmileLivenessUiElement,
} from "@innovatrics/dot-auto-capture-ui/smile-liveness";
import { useEffect } from "react";

function SmileLivenessUi(props: SmileLivenessUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-smile-liveness-ui",
    ) as HTMLSmileLivenessUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-smile-liveness-ui id="x-dot-smile-liveness-ui" />;
}

export default SmileLivenessUi;
