// vuejs-components-integration/src/components/SmileLivenessUi.vue
<script setup lang="ts">

import type { SmileLivenessUiProps } from "@innovatrics/dot-auto-capture-ui/smile-liveness";
import "@innovatrics/dot-auto-capture-ui/smile-liveness";

type Props = {
    uiProps: SmileLivenessUiProps
}
const props = defineProps<Props>()
</script>

<template>
    <x-dot-smile-liveness-ui .props="props.uiProps" id="x-dot-smile-liveness-ui" />
</template>

// reactjs-components-integration/src/components/SmileLivenessUi.tsx
import "@innovatrics/dot-auto-capture-ui/smile-liveness";

import type {
  SmileLivenessUiProps,
  HTMLSmileLivenessUiElement,
} from "@innovatrics/dot-auto-capture-ui/smile-liveness";
import { useEffect } from "react";

function SmileLivenessUi(props: SmileLivenessUiProps) {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-smile-liveness-ui",
    ) as HTMLSmileLivenessUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-smile-liveness-ui id="x-dot-smile-liveness-ui" />;
}

export default SmileLivenessUi;
