// reactjs-components-integration/src/components/FaceUi.tsx
import type {
  FaceUiProps,
  HTMLFacetUiElement,
} from "@innovatrics/dot-auto-capture-ui/face";
import { useEffect } from "react";
import "@innovatrics/dot-auto-capture-ui/face";

const FaceUi = (props: FaceUiProps) => {
  useEffect(() => {
    const uiElement = document.getElementById(
      "x-dot-face-auto-capture-ui"
    ) as HTMLFacetUiElement | null;

    if (uiElement) {
      uiElement.props = props;
    }
  });

  return <x-dot-face-auto-capture-ui id="x-dot-face-auto-capture-ui" />;
};

export default FaceUi;

// angular-components-integration/src/app/components/face-ui/face-ui.component.ts
import { Component, OnInit } from '@angular/core';
import { HTMLFacetUiElement } from '@innovatrics/dot-auto-capture-ui/face';
import '@innovatrics/dot-auto-capture-ui/face';

@Component({
  selector: 'app-face-ui',
  templateUrl: './face-ui.component.html',
  styleUrls: ['./face-ui.component.css'],
})
export class FaceUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initFaceUi();
  }

  initFaceUi() {
    const faceUiElement = document.getElementById(
      'dot-face-auto-capture-ui'
    ) as HTMLFacetUiElement | null;

    if (faceUiElement) {
      faceUiElement.props = {
        showCameraButtons: true,
      };
    }
  }
}

<x-dot-face-auto-capture-ui
  id="dot-face-auto-capture-ui"
></x-dot-face-auto-capture-ui>
