// reactjs-components-integration/src/components/ComponentSelect.tsx
import { Step } from "../types";
import styles from "../styles/button.module.css";

interface Props {
  setStep: (step: Step) => void;
}

function ComponentSelect({ setStep }: Props) {
  const handleDocumentClick = () => {
    setStep(Step.DOCUMENT_CAPTURE);
  };

  const handleFaceClick = () => {
    setStep(Step.FACE_CAPTURE);
  };

  const handleMagnifEyeLivenessClick = () => {
    setStep(Step.MAGNIFEYE_LIVENESS);
  };

  return (
    <div>
      <button className={styles.primary} onClick={handleDocumentClick}>
        Document
      </button>
      <button className={styles.primary} onClick={handleFaceClick}>
        Face
      </button>
      <button className={styles.primary} onClick={handleMagnifEyeLivenessClick}>
        MagnifEye Liveness
      </button>
    </div>
  );
}

export default ComponentSelect;

// vuejs-components-integration/src/components/ComponentSelect.vue
<script setup lang="ts">
import { Step } from "../types";

const emit = defineEmits<{
  (e: "onClick", step: Step): void;
}>();
</script>

<template>
  <div>
    <button class="button" @click="emit('onClick', Step.DOCUMENT_CAPTURE)">
      Document
    </button>
    <button class="button" @click="emit('onClick', Step.FACE_CAPTURE)">
      Face
    </button>
    <button class="button" @click="emit('onClick', Step.MAGNIFEYE_CAPTURE)">
      MagnifEye Liveness
    </button>
  </div>
</template>
