// angular-components-integration/src/app/components/document-auto-capture/document-auto-capture.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { OnPhotoTakenEventValue, Step } from 'src/app/types';
import {
  dispatchControlEvent,
  DocumentCustomEvent,
  ControlEventInstruction,
} from '@innovatrics/dot-document-auto-capture/events';
import { DocumentComponentData } from '@innovatrics/dot-document-auto-capture';

@Component({
  selector: 'app-document-auto-capture',
  templateUrl: './document-auto-capture.component.html',
})
export class DocumentAutoCaptureComponent implements OnInit {
  @Output() onPhotoTaken = new EventEmitter<OnPhotoTakenEventValue<DocumentComponentData>>();
  @Output() onError = new EventEmitter<Error>();
  @Output() onBack = new EventEmitter<Step>();

  isButtonDisabled = true;

  constructor() { }

  ngOnInit(): void { }

  onBackClick() {
    this.onBack.emit(Step.SELECT_COMPONENT);
  }

  handleContinue() {
    dispatchControlEvent(
      DocumentCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION
    );
    this.isButtonDisabled = true;
  }

  handlePhotoTaken({ image, data }: OnPhotoTakenEventValue<DocumentComponentData>) {
    this.onPhotoTaken.emit({ image, data });
    this.isButtonDisabled = false;
  }

  handleError(error: Error) {
    this.onError.emit(error);
  }
}

<div>
  <h2>Document auto capture</h2>
  <button (click)="onBackClick()" class="button">Go back</button>
  <button
    (click)="handleContinue()"
    class="button"
    [disabled]="isButtonDisabled"
  >
    Continue detection
  </button>
  <div class="container">
    <app-document-camera
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
    ></app-document-camera>
    <app-document-ui></app-document-ui>
  </div>
</div>

// vuejs-components-integration/src/components/DocumentAutoCapture.vue
<script setup lang="ts">
import { ref } from "vue";
import type { DocumentComponentData } from "@innovatrics/dot-document-auto-capture";
import {
  dispatchControlEvent,
  DocumentCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-document-auto-capture/events";
import { Step } from "../types";
import DocumentCamera from "./DocumentCamera.vue";
import DocumentUi from "./DocumentUi.vue";

const emit = defineEmits<{
  (e: "onPhotoTaken", image: Blob, data: DocumentComponentData): void;
  (e: "onError", error: Error): void;
  (e: "onBack", step: Step): void;
}>();

const isButtonDisabled = ref(true);

const handlePhotoTaken = (image: Blob, data: DocumentComponentData) => {
  isButtonDisabled.value = false;
  emit("onPhotoTaken", image, data);
};

const handleContinueDetection = () => {
  dispatchControlEvent(
    DocumentCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
};

const handleError = (error: Error) => {
  emit("onError", error);
};
</script>

<template>
  <div>
    <h2>Document auto capture</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button
      :disabled="isButtonDisabled"
      @click="handleContinueDetection"
      class="button"
    >
      Continue detection
    </button>
    <div class="container">
      <DocumentCamera
        :cameraOptions="{
          imageType: 'png',
          cameraFacing: 'environment',
          onPhotoTaken: handlePhotoTaken,
          onError: handleError,
        }"
      />
      <DocumentUi :uiProps="{showCameraButtons: true}" />
    </div>
  </div>
</template>
