// reactjs-components-integration/src/components/DocumentUi.tsx
import '@innovatrics/dot-auto-capture-ui/document';
import type { DocumentUiConfiguration, HTMLDocumentUiElement } from '@innovatrics/dot-auto-capture-ui/document';

import { useEffect } from 'react';

function DocumentUi(configuration: DocumentUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-document-auto-capture-ui') as HTMLDocumentUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-document-auto-capture-ui id="x-dot-document-auto-capture-ui" />;
}

export default DocumentUi;

// vuejs-components-integration/src/components/DocumentUi.vue
<script setup lang="ts">
import type { DocumentUiConfiguration } from "@innovatrics/dot-auto-capture-ui/document";
import "@innovatrics/dot-auto-capture-ui/document";

type Props = {
  configuration: DocumentUiConfiguration;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-document-auto-capture-ui .configuration="props.configuration" id="x-dot-document-auto-capture-ui"/>
</template>
