// react-components-integration/src/components/FaceUi.tsx
import type { FaceUiConfiguration, HTMLFacetUiElement } from '@innovatrics/dot-auto-capture-ui/face';

import { useEffect } from 'react';
import '@innovatrics/dot-auto-capture-ui/face';

function FaceUi(configuration: FaceUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-face-auto-capture-ui') as HTMLFacetUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-face-auto-capture-ui id="x-dot-face-auto-capture-ui" />;
}

export default FaceUi;

// vuejs-components-integration/src/components/FaceUi.vue
<script setup lang="ts">
import type { FaceUiConfiguration } from "@innovatrics/dot-auto-capture-ui/face";
import "@innovatrics/dot-auto-capture-ui/face";

type Props = {
  configuration: FaceUiConfiguration;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-face-auto-capture-ui .configuration="props.configuration" id="x-dot-face-auto-capture-ui" />
</template>
