// reactjs-components-integration/src/components/FaceAutoCapture.tsx
import type {
  FaceCallback,
  FaceComponentData,
} from "@innovatrics/dot-face-auto-capture";
import {
  dispatchControlEvent,
  FaceCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-face-auto-capture/events";
import { useState } from "react";
import styles from "../styles/index.module.css";
import buttonStyles from "../styles/button.module.css";
import FaceCamera from "./FaceCamera";
import FaceUi from "./FaceUi";

interface Props {
  onPhotoTaken: FaceCallback;
  onError: (error: Error) => void;
  onBackClick: () => void;
}

const FaceAutoCapture = ({ onPhotoTaken, onError, onBackClick }: Props) => {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  const handlePhotoTaken = (image: Blob, data: FaceComponentData) => {
    setIsButtonDisabled(false);
    onPhotoTaken(image, data);
  };

  const handleContinueDetection = () => {
    dispatchControlEvent(
      FaceCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION
    );

    setIsButtonDisabled(true);
  };
  return (
    <>
      <h2>Face auto capture</h2>
      <div>
        <button
          className={buttonStyles.primary}
          onClick={handleContinueDetection}
          disabled={isButtonDisabled}
        >
          Continue detection
        </button>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Back
        </button>
      </div>
      <div className={styles.container}>
        <FaceCamera
          imageType="png"
          cameraFacing="user"
          onPhotoTaken={handlePhotoTaken}
          onError={onError}
        />
        <FaceUi showCameraButtons/>
      </div>
    </>
  );
};

export default FaceAutoCapture;

// vuejs-components-integration/src/components/FaceAutoCapture.vue
<script setup lang="ts">
import { ref } from "vue";
import type { FaceComponentData } from "@innovatrics/dot-face-auto-capture";
import {
  dispatchControlEvent,
  FaceCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-face-auto-capture/events";
import { Step } from "../types";
import FaceCamera from "./FaceCamera.vue";
import FaceUi from "./FaceUi.vue";

const emit = defineEmits<{
  (e: "onPhotoTaken", image: Blob, data: FaceComponentData): void;
  (e: "onError", error: Error): void;
  (e: "onBack", step: Step): void;
}>();

const isButtonDisabled = ref(true);

const handlePhotoTaken = (image: Blob, data: FaceComponentData) => {
  isButtonDisabled.value = false;
  emit("onPhotoTaken", image, data);
};

const handleContinueDetection = () => {
  dispatchControlEvent(
    FaceCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
};

const handleError = (error: Error) => {
  emit("onError", error);
};
</script>

<template>
  <div>
    <h2>Face auto capture</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button
      :disabled="isButtonDisabled"
      @click="handleContinueDetection"
      class="button"
    >
      Continue detection
    </button>
    <div class="container">
      <FaceCamera
        :cameraOptions="{
          imageType: 'png',
          cameraFacing: 'user',
          onPhotoTaken: handlePhotoTaken,
          onError: handleError,
        }"
      />
      <FaceUi :uiProps="{showCameraButtons: true}" />
    </div>
  </div>
</template>
