// angular-components-integration/src/app/components/face/face-auto-capture.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { OnPhotoTakenEventValue, Step } from '../../types';
import {
  dispatchControlEvent,
  FaceCustomEvent,
  ControlEventInstruction,
} from '@innovatrics/dot-face-auto-capture/events';
import { DetectedFace } from '@innovatrics/dot-face-auto-capture';
import { FaceCameraComponent } from './face-camera.component';
import { FaceUiComponent } from './face-ui.component';

@Component({
  selector: 'app-face-auto-capture',
  standalone: true,
  imports: [FaceCameraComponent, FaceUiComponent],
  template: `
    <div>
      <h2>Face auto capture</h2>
      <button (click)="onBackClick()" class="button">Go back</button>
      <button
        (click)="handleContinue()"
        class="button"
        [disabled]="isButtonDisabled"
      >
        Continue detection
      </button>
      <div class="container">
        <app-face-camera
          (photoTaken)="handlePhotoTaken($event)"
          (captureError)="handleError($event)"
        ></app-face-camera>
        <app-face-ui></app-face-ui>
      </div>
    </div>
  `,
})
export class FaceAutoCaptureComponent {
  @Output() photoTaken = new EventEmitter<
    OnPhotoTakenEventValue<DetectedFace>
  >();
  @Output() captureError = new EventEmitter<Error>();
  @Output() back = new EventEmitter<Step>();

  isButtonDisabled = true;

  onBackClick() {
    this.back.emit(Step.SELECT_COMPONENT);
  }

  handleContinue() {
    dispatchControlEvent(
      FaceCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION,
    );
    this.isButtonDisabled = true;
  }

  handlePhotoTaken({
    imageData,
    content,
  }: OnPhotoTakenEventValue<DetectedFace>) {
    this.photoTaken.emit({ imageData, content });
    this.isButtonDisabled = false;
  }

  handleError(error: Error) {
    this.captureError.emit(error);
  }
}

// vuejs-components-integration/src/components/FaceAutoCapture.vue
<script setup lang="ts">
import { ref } from "vue";
import type { FaceOnCompleteCallback, FaceOnCompleteCallbackImage } from "@innovatrics/dot-face-auto-capture";
import {
  dispatchControlEvent,
  FaceCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-face-auto-capture/events";
import { Step, Emits } from "../types";
import FaceCamera from "./FaceCamera.vue";
import FaceUi from "./FaceUi.vue";

const emit = defineEmits<Emits<FaceOnCompleteCallback>>();

const isButtonDisabled = ref(true);

function handlePhotoTaken(imageData: FaceOnCompleteCallbackImage, content: Uint8Array) {
  isButtonDisabled.value = false;
  emit("onComplete", imageData, content);
}

function handleContinueDetection() {
  dispatchControlEvent(
    FaceCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
}

function handleError(error: Error) {
  emit("onError", error);
}
</script>

<template>
  <div>
    <h2>Face auto capture</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button :disabled="isButtonDisabled" @click="handleContinueDetection" class="button">
      Continue detection
    </button>
    <div class="container overflow-hidden">
      <FaceCamera :configuration="{
        camera: { facingMode: 'user' },
        onComplete: handlePhotoTaken,
        onError: handleError,
      }" />
      <FaceUi :configuration="{ control: { showCameraButtons: true } }" />
    </div>
  </div>
</template>
