// reactjs-components-integration/src/components/MagnifEyeLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';
import type {
  HTMLMagnifEyeLivenessUiElement,
  MagnifEyeLivenessUiConfiguration,
} from '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';

import { useEffect } from 'react';

function MagnifEyeLivenessUi(configuration: MagnifEyeLivenessUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-magnifeye-liveness-ui') as HTMLMagnifEyeLivenessUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-magnifeye-liveness-ui id="x-dot-magnifeye-liveness-ui" />;
}

export default MagnifEyeLivenessUi;

// vuejs-components-integration/src/components/MagnifEyeLivenessUi.vue
<script setup lang="ts">
import type { MagnifEyeLivenessUiConfiguration } from "@innovatrics/dot-auto-capture-ui/magnifeye-liveness";
import "@innovatrics/dot-auto-capture-ui/magnifeye-liveness";

type Props = {
  configuration: MagnifEyeLivenessUiConfiguration;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-magnifeye-liveness-ui .configuration="props.configuration" id="x-dot-magnifeye-liveness-ui" />
</template>
