// reactjs-components-integration/src/components/MultiRangeLivenessCamera.tsx
import '@innovatrics/dot-multi-range-liveness';
import type { Configuration, HTMLMultiRangeLivenessElement } from '@innovatrics/dot-multi-range-liveness';

import { useEffect } from 'react';

function MultiRangeLivenessCamera(configuration: Configuration) {
  useEffect(() => {
    const multiRangeLivenessHTMLElement = document.getElementById(
      'x-dot-multi-range-liveness'
    ) as HTMLMultiRangeLivenessElement | null;

    if (multiRangeLivenessHTMLElement) {
      multiRangeLivenessHTMLElement.configuration = configuration;
    }
  });

  return <x-dot-multi-range-liveness id="x-dot-multi-range-liveness" />;
}

export default MultiRangeLivenessCamera;

// vuejs-components-integration/src/components/MultiRangeLivenessCamera.vue
<script setup lang="ts">
import type { Configuration } from '@innovatrics/dot-multi-range-liveness';
import '@innovatrics/dot-multi-range-liveness';

type Props = {
  configuration: Configuration;
};
const props = defineProps<Props>();
</script>

<template>
  <x-dot-multi-range-liveness .configuration="props.configuration" id="x-dot-multi-range-liveness" />
</template>
