// react-components-integration/src/components/SmileLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/smile-liveness';

import type {
  SmileLivenessUiConfiguration,
  HTMLSmileLivenessUiElement,
} from '@innovatrics/dot-auto-capture-ui/smile-liveness';
import { useEffect } from 'react';

function SmileLivenessUi(configuration: SmileLivenessUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-smile-liveness-ui') as HTMLSmileLivenessUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-smile-liveness-ui id="x-dot-smile-liveness-ui" />;
}

export default SmileLivenessUi;

// vuejs-components-integration/src/components/SmileLivenessUi.vue
<script setup lang="ts">

import type { SmileLivenessUiConfiguration } from "@innovatrics/dot-auto-capture-ui/smile-liveness";
import "@innovatrics/dot-auto-capture-ui/smile-liveness";

type Props = {
    configuration: SmileLivenessUiConfiguration
}
const props = defineProps<Props>()
</script>

<template>
    <x-dot-smile-liveness-ui .configuration="props.configuration" id="x-dot-smile-liveness-ui" />
</template>
