// reactjs-components-integration/src/components/SmileLiveness.tsx
import type { OnCompleteCallback, OnCompleteCallbackImages } from '@innovatrics/dot-smile-liveness';

import { useState } from 'react';
import {
  dispatchControlEvent,
  SmileCustomEvent,
  ControlEventInstruction,
} from '@innovatrics/dot-smile-liveness/events';

import styles from '../styles/index.module.css';
import buttonStyles from '../styles/button.module.css';
import SmileLivenessCamera from './SmileLivenessCamera';
import SmileLivenessUi from './SmileLivenessUi';

interface Props {
  onComplete: OnCompleteCallback;
  onError: (error: Error) => void;
  onBackClick: () => void;
}

function SmileLiveness({ onBackClick, onComplete, onError }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  function handleOnComplete(imageData: OnCompleteCallbackImages, content: Uint8Array) {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  }

  const handleContinueDetection = () => {
    dispatchControlEvent(SmileCustomEvent.CONTROL, ControlEventInstruction.CONTINUE_DETECTION);

    setIsButtonDisabled(true);
  };

  return (
    <>
      <h2>Smile Liveness</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button className={buttonStyles.primary} onClick={handleContinueDetection} disabled={isButtonDisabled}>
          Continue detection
        </button>
      </div>
      <div className={styles.container}>
        <SmileLivenessCamera onComplete={handleOnComplete} onError={onError} />
        <SmileLivenessUi control={{ showCameraButtons: true }} />
      </div>
    </>
  );
}

export default SmileLiveness;

// vuejs-components-integration/src/components/SmileLiveness.vue
<script setup lang="ts">
import { ref } from "vue";
import { Step, Emits } from "../types";
import SmileLivenessCamera from "./SmileLivenessCamera.vue";
import SmileLivenessUi from "./SmileLivenessUi.vue";
import { OnCompleteCallback, OnCompleteCallbackImages } from "@innovatrics/dot-smile-liveness";
import {
  dispatchControlEvent,
  SmileCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-smile-liveness/events";

const emit = defineEmits<Emits<OnCompleteCallback>>();
const isButtonDisabled = ref(true);

/**
 * At this point use @content property with Digital Identity Service in order to evaluate the Smile liveness score.
 */
function onComplete(imageData: OnCompleteCallbackImages, content: Uint8Array) {
  isButtonDisabled.value = false;
  emit("onComplete", imageData, content);
}

function handleContinueDetection() {
  dispatchControlEvent(
    SmileCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
}

function onError(error: Error) {
  emit("onError", error);
}
</script>

<template>
  <div>
    <h2>Smile Liveness</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button :disabled="isButtonDisabled" @click="handleContinueDetection" class="button">
      Continue detection
    </button>
    <div class="container overflow-hidden">
      <SmileLivenessCamera :configuration="{
        onComplete: onComplete,
        onError: onError,
      }" />
      <SmileLivenessUi :configuration="{ control: { showCameraButtons: true } }" />
    </div>
  </div>
</template>
