// reactjs-components-integration/src/components/MagnifEyeLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';
import type {
  HTMLMagnifEyeLivenessUiElement,
  MagnifEyeLivenessUiConfiguration,
} from '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';

import { useEffect } from 'react';

function MagnifEyeLivenessUi(configuration: MagnifEyeLivenessUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-magnifeye-liveness-ui') as HTMLMagnifEyeLivenessUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-magnifeye-liveness-ui id="x-dot-magnifeye-liveness-ui" />;
}

export default MagnifEyeLivenessUi;

// angular-components-integration/src/app/components/magnifeye-liveness/magnifeye-liveness-ui.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnInit } from '@angular/core';
import type { HTMLMagnifEyeLivenessUiElement } from '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';
import '@innovatrics/dot-auto-capture-ui/magnifeye-liveness';

@Component({
  selector: 'app-magnifeye-liveness-ui',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <x-dot-magnifeye-liveness-ui
      id="x-dot-magnifeye-liveness-ui"
    ></x-dot-magnifeye-liveness-ui>
  `,
})
export class MagnifEyeLivenessUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initMagnifEyeLivenessUi();
  }

  initMagnifEyeLivenessUi() {
    const magnifEyeUiElement = document.getElementById(
      'x-dot-magnifeye-liveness-ui',
    ) as HTMLMagnifEyeLivenessUiElement | null;

    if (magnifEyeUiElement) {
      magnifEyeUiElement.configuration = {
        control: {
          showCameraButtons: true,
        },
      };
    }
  }
}
