// reactjs-components-integration/src/components/MagnifEyeLiveness.tsx
import type { MagnifEyeLivenessCallback } from "@innovatrics/dot-magnifeye-liveness";
import { useState } from "react";
import {
  dispatchControlEvent,
  MagnifEyeCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-magnifeye-liveness/events";
import styles from "../styles/index.module.css";
import buttonStyles from "../styles/button.module.css";
import MagnifEyeLivenessCamera from "./MagnifEyeLivenessCamera";
import MagnifEyeLivenessUi from "./MagnifEyeLivenessUi";

interface Props {
  onComplete: MagnifEyeLivenessCallback;
  onError: (error: Error) => void;
  onBackClick: () => void;
}

function MagnifEyeLiveness({ onBackClick, onComplete, onError }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  const handleOnComplete: MagnifEyeLivenessCallback = async (
    imageData,
    content,
  ) => {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  };

  const handleContinueDetection = () => {
    dispatchControlEvent(
      MagnifEyeCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION,
    );

    setIsButtonDisabled(true);
  };
  return (
    <>
      <h2>MagnifEye Liveness</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button
          className={buttonStyles.primary}
          onClick={handleContinueDetection}
          disabled={isButtonDisabled}
        >
          Continue detection
        </button>
      </div>
      <div className={styles.container}>
        <MagnifEyeLivenessCamera
          onComplete={handleOnComplete}
          onError={onError}
        />
        <MagnifEyeLivenessUi showCameraButtons />
      </div>
    </>
  );
}

export default MagnifEyeLiveness;

// angular-components-integration/src/app/components/magnifeye-liveness/magnifeye-liveness.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { OnPhotoTakenEventValue, Step } from '../../types';
import type { OnCompleteData } from '@innovatrics/dot-magnifeye-liveness';
import { MagnifEyeLivenessCameraComponent } from './magnifeye-liveness-camera.component';
import { MagnifEyeLivenessUiComponent } from './magnifeye-liveness-ui.component';
import {
  dispatchControlEvent,
  MagnifEyeCustomEvent,
  ControlEventInstruction,
} from '@innovatrics/dot-magnifeye-liveness/events';
@Component({
  selector: 'app-magnifeye-liveness',
  standalone: true,
  imports: [MagnifEyeLivenessCameraComponent, MagnifEyeLivenessUiComponent],
  template: `
    <div>
      <h2>MagnifEye Liveness</h2>
      <button (click)="onBackClick()" class="button">Go back</button>
      <button
        (click)="handleContinue()"
        class="button"
        [disabled]="isButtonDisabled"
      >
        Continue detection
      </button>
      <div class="container">
        <app-magnifeye-liveness-camera
          (photoTaken)="handlePhotoTaken($event)"
          (captureError)="handleError($event)"
        ></app-magnifeye-liveness-camera>
        <app-magnifeye-liveness-ui></app-magnifeye-liveness-ui>
      </div>
    </div>
  `,
})
export class MagnifEyeLivenessComponent {
  @Output() photoTaken = new EventEmitter<
    OnPhotoTakenEventValue<OnCompleteData['data']>
  >();
  @Output() captureError = new EventEmitter<Error>();
  @Output() back = new EventEmitter<Step>();

  isButtonDisabled = true;

  onBackClick() {
    this.back.emit(Step.SELECT_COMPONENT);
  }

  handleContinue() {
    dispatchControlEvent(
      MagnifEyeCustomEvent.CONTROL,
      ControlEventInstruction.CONTINUE_DETECTION,
    );
    this.isButtonDisabled = true;
  }

  handlePhotoTaken({
    imageData,
    content,
  }: OnPhotoTakenEventValue<OnCompleteData['data']>) {
    this.photoTaken.emit({ imageData, content });
    this.isButtonDisabled = false;
  }

  handleError(error: Error) {
    this.captureError.emit(error);
  }
}

<div>
  <h2>MagnifEye Liveness</h2>
  <button (click)="onBackClick()" class="button">Go back</button>
  <div class="container">
    <app-magnifeye-liveness-camera
      (onPhotoTaken)="handlePhotoTaken($event)"
      (onError)="handleError($event)"
    ></app-magnifeye-liveness-camera>
    <app-magnifeye-liveness-ui></app-magnifeye-liveness-ui>
  </div>
</div>
