// vuejs-components-integration/src/components/DocumentAutoCapture.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  dispatchControlEvent,
  DocumentCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-document-auto-capture/events";
import { Step, Emits } from "../types";
import DocumentCamera from "./DocumentCamera.vue";
import DocumentUi from "./DocumentUi.vue";
import { DocumentOnCompleteCallback, DocumentOnCompleteCallbackImage } from '@innovatrics/dot-document-auto-capture';


const emit = defineEmits<Emits<DocumentOnCompleteCallback>>();

const isButtonDisabled = ref(true);

function handlePhotoTaken(imageData: DocumentOnCompleteCallbackImage, content: Uint8Array) {
  isButtonDisabled.value = false;
  emit("onComplete", imageData, content);
}

function handleContinueDetection() {
  dispatchControlEvent(
    DocumentCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
}

function handleError(error: Error) {
  emit("onError", error);
}
</script>

<template>
  <div>
    <h2>Document auto capture</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button :disabled="isButtonDisabled" @click="handleContinueDetection" class="button">
      Continue detection
    </button>
    <div class="container overflow-hidden">
      <DocumentCamera :configuration="{
        camera: { facingMode: 'environment' },
        onComplete: handlePhotoTaken,
        onError: handleError,
      }" />
      <DocumentUi :configuration="{ control: { showCameraButtons: true } }" />
    </div>
  </div>
</template>

// react-components-integration/src/components/DocumentAutoCapture.tsx
import type {
  DocumentOnCompleteCallback,
  DocumentOnCompleteCallbackImage,
} from '@innovatrics/dot-document-auto-capture';

import {
  ControlEventInstruction,
  dispatchControlEvent,
  DocumentCustomEvent,
} from '@innovatrics/dot-document-auto-capture/events';
import { useState } from 'react';

import buttonStyles from '../styles/button.module.css';
import styles from '../styles/index.module.css';

import DocumentCamera from './DocumentCamera';
import DocumentUi from './DocumentUi';

interface Props {
  onBackClick: () => void;
  onError: (error: Error) => void;
  onComplete: DocumentOnCompleteCallback;
}

function DocumentAutoCapture({ onBackClick, onError, onComplete }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  function handlePhotoTaken(imageData: DocumentOnCompleteCallbackImage, content: Uint8Array) {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  }

  const handleContinueDetection = () => {
    dispatchControlEvent(DocumentCustomEvent.CONTROL, ControlEventInstruction.CONTINUE_DETECTION);

    setIsButtonDisabled(true);
  };

  return (
    <>
      <h2>Document auto capture</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button className={buttonStyles.primary} disabled={isButtonDisabled} onClick={handleContinueDetection}>
          Continue detection
        </button>
      </div>
      {/* parent container must have position: relative */}
      <div className={styles.container}>
        <DocumentCamera camera={{ facingMode: 'environment' }} onComplete={handlePhotoTaken} onError={onError} />
        <DocumentUi control={{ showCameraButtons: true }} />
      </div>
    </>
  );
}

export default DocumentAutoCapture;
