// vuejs-components-integration/src/components/MagnifEyeLiveness.vue
<script setup lang="ts">
import { ref } from "vue";
import { Step, Emits } from "../types";
import MagnifEyeLivenessCamera from "./MagnifEyeLivenessCamera.vue";
import MagnifEyeLivenessUi from "./MagnifEyeLivenessUi.vue";
import { MagnifEyeLivenessOnCompleteCallback, MagnifEyeLivenessOnCompleteCallbackImage } from "@innovatrics/dot-magnifeye-liveness";
import {
  dispatchControlEvent,
  MagnifEyeCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-magnifeye-liveness/events";

const emit = defineEmits<Emits<MagnifEyeLivenessOnCompleteCallback>>();

const isButtonDisabled = ref(true);

/**
 * At this point use @content property with Digital Identity Service in order to evaluate the MagnifEye liveness score.
 * See: https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-dis/latest/documentation/#_magnifeye_liveness_check
 */
function onComplete(imageData: MagnifEyeLivenessOnCompleteCallbackImage, content: Uint8Array) {
  isButtonDisabled.value = false;
  emit("onComplete", imageData, content);
}

function handleContinueDetection() {
  dispatchControlEvent(
    MagnifEyeCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
}

function onError(error: Error) {
  emit("onError", error);
}
</script>

<template>
  <div>
    <h2>MagnifEye Liveness</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button :disabled="isButtonDisabled" @click="handleContinueDetection" class="button">
      Continue detection
    </button>
    <div class="container overflow-hidden">
      <MagnifEyeLivenessCamera :configuration="{
        onComplete: onComplete,
        onError: onError,
      }" />
      <MagnifEyeLivenessUi :configuration="{ control: { showCameraButtons: true } }" />
    </div>
  </div>
</template>

// react-components-integration/src/components/MagnifEyeLiveness.tsx
import type {
  MagnifEyeLivenessOnCompleteCallback,
  MagnifEyeLivenessOnCompleteCallbackImage,
} from '@innovatrics/dot-magnifeye-liveness';

import {
  ControlEventInstruction,
  dispatchControlEvent,
  MagnifEyeCustomEvent,
} from '@innovatrics/dot-magnifeye-liveness/events';
import { useState } from 'react';

import buttonStyles from '../styles/button.module.css';
import styles from '../styles/index.module.css';

import MagnifEyeLivenessCamera from './MagnifEyeLivenessCamera';
import MagnifEyeLivenessUi from './MagnifEyeLivenessUi';

interface Props {
  onBackClick: () => void;
  onComplete: MagnifEyeLivenessOnCompleteCallback;
  onError: (error: Error) => void;
}

function MagnifEyeLiveness({ onBackClick, onComplete, onError }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  async function handleOnComplete(imageData: MagnifEyeLivenessOnCompleteCallbackImage, content: Uint8Array) {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  }

  const handleContinueDetection = () => {
    dispatchControlEvent(MagnifEyeCustomEvent.CONTROL, ControlEventInstruction.CONTINUE_DETECTION);

    setIsButtonDisabled(true);
  };

  return (
    <>
      <h2>MagnifEye Liveness</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button className={buttonStyles.primary} disabled={isButtonDisabled} onClick={handleContinueDetection}>
          Continue detection
        </button>
      </div>
      <div className={styles.container}>
        <MagnifEyeLivenessCamera onComplete={handleOnComplete} onError={onError} />
        <MagnifEyeLivenessUi control={{ showCameraButtons: true }} />
      </div>
    </>
  );
}

export default MagnifEyeLiveness;
