// vuejs-components-integration/src/components/PalmCapture.vue
<script setup lang="ts">
import { ref } from "vue";
import type { PalmOnCompleteCallback, PalmOnCompleteCallbackImage } from "@innovatrics/dot-palm-capture";
import {
  dispatchControlEvent,
  PalmCustomEvent,
  ControlEventInstruction,
} from "@innovatrics/dot-palm-capture/events";
import { Step, Emits } from "../types";
import PalmCamera from "./PalmCamera.vue";
import PalmUi from "./PalmUi.vue";


const emit = defineEmits<Emits<PalmOnCompleteCallback>>();

const isButtonDisabled = ref(true);

function handlePhotoTaken(imageData: PalmOnCompleteCallbackImage, content: Uint8Array) {
  isButtonDisabled.value = false;
  emit("onComplete", imageData, content);
}

function handleContinueDetection() {
  dispatchControlEvent(
    PalmCustomEvent.CONTROL,
    ControlEventInstruction.CONTINUE_DETECTION
  );
  isButtonDisabled.value = true;
}

function handleError(error: Error) {
  emit("onError", error);
}
</script>

<template>
  <div>
    <h2>Palm auto capture</h2>
    <button @click="emit('onBack', Step.SELECT_COMPONENT)" class="button">
      Go back
    </button>
    <button :disabled="isButtonDisabled" @click="handleContinueDetection" class="button">
      Continue detection
    </button>
    <div class="container">
      <PalmCamera :configuration="{
        camera: { facingMode: 'environment' },
        onComplete: handlePhotoTaken,
        onError: handleError,
      }" />
      <PalmUi :configuration="{ control: { showCameraButtons: true } }" />
    </div>
  </div>
</template>

// react-components-integration/src/components/PalmCapture.tsx
import type { PalmOnCompleteCallback, PalmOnCompleteCallbackImage } from '@innovatrics/dot-palm-capture';

import { ControlEventInstruction, dispatchControlEvent, PalmCustomEvent } from '@innovatrics/dot-palm-capture/events';
import { useState } from 'react';

import buttonStyles from '../styles/button.module.css';
import styles from '../styles/index.module.css';

import PalmCamera from './PalmCamera';
import PalmUi from './PalmUi';

interface Props {
  onBackClick: () => void;
  onError: (error: Error) => void;
  onComplete: PalmOnCompleteCallback;
}

function PalmCapture({ onBackClick, onError, onComplete }: Props) {
  const [isButtonDisabled, setIsButtonDisabled] = useState(true);

  async function handlePhotoTaken(imageData: PalmOnCompleteCallbackImage, content: Uint8Array) {
    setIsButtonDisabled(false);
    onComplete(imageData, content);
  }

  const handleContinueDetection = () => {
    dispatchControlEvent(PalmCustomEvent.CONTROL, ControlEventInstruction.CONTINUE_DETECTION);

    setIsButtonDisabled(true);
  };

  return (
    <>
      <h2>Palm auto capture</h2>
      <div>
        <button className={buttonStyles.primary} onClick={onBackClick}>
          Go back
        </button>
        <button className={buttonStyles.primary} disabled={isButtonDisabled} onClick={handleContinueDetection}>
          Continue detection
        </button>
      </div>
      {/* parent container must have position: relative */}
      <div className={styles.container}>
        <PalmCamera camera={{ facingMode: 'environment' }} onComplete={handlePhotoTaken} onError={onError} />
        <PalmUi control={{ showCameraButtons: true }} />
      </div>
    </>
  );
}

export default PalmCapture;
