// react-components-integration/src/components/SmileLivenessUi.tsx
import '@innovatrics/dot-auto-capture-ui/smile-liveness';

import type {
  SmileLivenessUiConfiguration,
  HTMLSmileLivenessUiElement,
} from '@innovatrics/dot-auto-capture-ui/smile-liveness';
import { useEffect } from 'react';

function SmileLivenessUi(configuration: SmileLivenessUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-smile-liveness-ui') as HTMLSmileLivenessUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-smile-liveness-ui id="x-dot-smile-liveness-ui" />;
}

export default SmileLivenessUi;

// angular-components-integration/src/app/components/smile-liveness/smile-liveness-ui.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnInit } from '@angular/core';
import type { HTMLSmileLivenessUiElement } from '@innovatrics/dot-auto-capture-ui/smile-liveness';
import '@innovatrics/dot-auto-capture-ui/smile-liveness';

@Component({
  selector: 'app-smile-liveness-ui',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <x-dot-smile-liveness-ui
      id="x-dot-smile-liveness-ui"
    ></x-dot-smile-liveness-ui>
  `,
})
export class SmileLivenessUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initSmileLivenessUi();
  }

  initSmileLivenessUi() {
    const smileUiElement = document.getElementById(
      'x-dot-smile-liveness-ui',
    ) as HTMLSmileLivenessUiElement | null;

    if (smileUiElement) {
      smileUiElement.configuration = {
        control: {
          showCameraButtons: true,
        },
      };
    }
  }
}
