// react-components-integration/src/components/FaceUi.tsx
import type { FaceUiConfiguration, HTMLFacetUiElement } from '@innovatrics/dot-auto-capture-ui/face';

import { useEffect } from 'react';
import '@innovatrics/dot-auto-capture-ui/face';

function FaceUi(configuration: FaceUiConfiguration) {
  useEffect(() => {
    const uiElement = document.getElementById('x-dot-face-auto-capture-ui') as HTMLFacetUiElement | null;

    if (uiElement) {
      uiElement.configuration = configuration;
    }
  });

  return <x-dot-face-auto-capture-ui id="x-dot-face-auto-capture-ui" />;
}

export default FaceUi;

// angular-components-integration/src/app/components/face/face-ui.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnInit } from '@angular/core';
import { HTMLFacetUiElement } from '@innovatrics/dot-auto-capture-ui/face';
import '@innovatrics/dot-auto-capture-ui/face';

@Component({
  selector: 'app-face-ui',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <x-dot-face-auto-capture-ui
      id="x-dot-face-auto-capture-ui"
    ></x-dot-face-auto-capture-ui>
  `,
})
export class FaceUiComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    this.initFaceUi();
  }

  initFaceUi() {
    const faceUiElement = document.getElementById(
      'x-dot-face-auto-capture-ui',
    ) as HTMLFacetUiElement | null;

    if (faceUiElement) {
      faceUiElement.configuration = {
        control: {
          showCameraButtons: true,
        },
      };
    }
  }
}
