// vuejs-components-integration/src/components/Result.vue
<template>
  <div>
    <div class="container">
      <button @click="onBackClick()" class="select-component-btn">
        Go back
      </button>
      <img :src="imageSrc" alt="result-picture" class="result-img" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Step } from "../types";

export default defineComponent({
  name: "Result",
  props: {
    imageSrc: String,
  },
  methods: {
    onBackClick() {
      this.$emit("onBack", Step.SELECT_COMPONENT);
    },
  },
});
</script>

<style scoped>
.result-img {
  width: 100%;
}
</style>

// angular-components-integration/src/app/components/result/result.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { Step } from 'src/app/types';
@Component({
  selector: 'app-result',
  templateUrl: './result.component.html',
  styleUrls: ['./result.component.css']
})
export class ResultComponent implements OnInit {
  @Input() imageUrl!: string;
  @Output() backBtnClick = new EventEmitter<Step>();

  imageSrc: SafeUrl = '';

  constructor(private domSanitizer: DomSanitizer) { }

  ngOnInit(): void {
    this.imageSrc = this.domSanitizer.bypassSecurityTrustUrl(this.imageUrl)
  }

  onBackClick() {
    this.backBtnClick.emit(Step.SELECT_COMPONENT)
  }

}

<div class="container">
  <button
    (click)="onBackClick()"
    class="select-component-btn"
  >
    Go back
  </button>
  <img
    [src]="imageSrc"
    alt="result-image"
    class="result-img"
  >
</div>
